import { test } from 'node:test';
import assert from 'node:assert/strict';
import { parseFrontmatter, classifySkill, renderCatalog, counts, applyCounts, targets } from './build-catalog.mjs';

test('parseFrontmatter reads top-level scalar keys', () => {
  const fm = parseFrontmatter('---\nname: x\ndescription: does y\ncontext: fork\n---\nbody');
  assert.equal(fm.name, 'x');
  assert.equal(fm.description, 'does y');
  assert.equal(fm.context, 'fork');
});

test('classifySkill derives kind from frontmatter only', () => {
  assert.equal(classifySkill({ context: 'fork' }), 'scaffolder');
  assert.equal(classifySkill({ 'disable-model-invocation': 'true' }), 'utility');
  assert.equal(classifySkill({ description: 'patterns' }), 'reference');
});

test('renderCatalog and counts summarize a scan result', () => {
  const data = {
    skills: [
      { name: 'laravel-database', kind: 'reference', description: 'db' },
      { name: 'laravel-feature', kind: 'scaffolder', description: 'feature' },
      { name: 'git-commit', kind: 'utility', description: 'commit' },
    ],
    agents: ['laravel-feature'],
  };
  assert.deepEqual(counts(data), { skills: 3, agents: 1 });
  const md = renderCatalog(data);
  assert.match(md, /GENERATED by scripts\/build-catalog\.mjs/);
  assert.match(md, /3 skills/);
  assert.match(md, /git-commit/);
});

test('parseFrontmatter handles folded block scalar (description: >)', () => {
  const yaml = '---\nname: laravel-api\ndescription: >\n  Build REST APIs with versioning.\n  Use for API endpoints.\ncontext: fork\n---\nbody';
  const fm = parseFrontmatter(yaml);
  assert.equal(fm.name, 'laravel-api');
  assert.match(fm.description, /Build REST APIs/);
  assert.equal(fm.context, 'fork');
});

test('applyCounts replaces only the marker block', () => {
  const src = 'intro\n<!-- catalog:counts -->OLD<!-- /catalog:counts -->\noutro';
  const out = applyCounts(src, { skills: [1, 2], agents: [1] });
  assert.match(out, /<!-- catalog:counts -->2 skills · 1 agents<!-- \/catalog:counts -->/);
  assert.match(out, /intro/);
  assert.match(out, /outro/);
});

test('targets() docs/index.html transform replaces stale agent/command/skill phrase with badge', () => {
  const data = {
    skills: new Array(12).fill({ name: 'x', kind: 'reference', description: '' }),
    agents: new Array(23).fill('a'),
  };
  const entry = targets(data).find((e) => e.path === 'docs/index.html');
  const stale = 'description: AI-powered Laravel development assistant for Claude Code with 23 agents, 42 commands, 12 skills, and 7 hooks.';
  const out = entry.fn(stale);
  assert.match(out, /12 skills, 23 agents/);
  assert.ok(!out.match(/23 agents, 42 commands, 12 skills/), 'stale phrase should be gone');
  assert.match(out, /and 7 hooks/, 'hook mention must be preserved');
});

test('targets() docs/commands.html transform replaces stale command count with badge', () => {
  const data = {
    skills: new Array(12).fill({ name: 'x', kind: 'reference', description: '' }),
    agents: new Array(23).fill('a'),
  };
  const entry = targets(data).find((e) => e.path === 'docs/commands.html');
  const stale1 = 'description: 47 commands for Laravel development with Claude Code';
  const stale2 = '        <p class="text-muted-foreground">47 commands for Laravel development with Claude Code</p>';
  assert.match(entry.fn(stale1), /12 skills, 23 agents for Laravel development/);
  assert.match(entry.fn(stale2), /12 skills, 23 agents for Laravel development/);
  assert.ok(!entry.fn(stale1).match(/47 commands/), 'stale phrase should be gone');
});

test('docs count targets refresh and are idempotent (no silent freeze)', () => {
  const data = { skills: new Array(65), agents: new Array(11) };
  const badge = '65 skills, 11 agents';
  for (const path of ['docs/index.html', 'docs/commands.html']) {
    const fn = targets(data).find((t) => t.path === path).fn;
    // a file already in badge form (with STALE counts) must refresh, not freeze:
    const refreshed = fn('prefix 22 skills, 30 agents suffix');
    assert.ok(refreshed.includes(badge), `${path} froze instead of refreshing stale counts`);
    // and applying the transform again must be a no-op:
    assert.equal(fn(refreshed), refreshed, `${path} transform not idempotent`);
  }
});
