#!/usr/bin/env node
import { readdirSync, readFileSync, existsSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

export function parseFrontmatter(text) {
  const m = text.match(/^---\n([\s\S]*?)\n---/);
  if (!m) return {};
  const out = {};
  for (const line of m[1].split('\n')) {
    const mm = line.match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (mm) out[mm[1]] = mm[2].trim().replace(/^["']|["']$/g, '');
  }
  return out;
}

export function classifySkill(fm) {
  if (String(fm.context || '').includes('fork')) return 'scaffolder';
  if (String(fm['disable-model-invocation'] || '') === 'true') return 'utility';
  return 'reference';
}

export function scan(root = ROOT) {
  const skills = [];
  const skillsDir = join(root, 'skills');
  if (existsSync(skillsDir)) {
    for (const name of readdirSync(skillsDir)) {
      const p = join(skillsDir, name, 'SKILL.md');
      if (existsSync(p)) {
        const fm = parseFrontmatter(readFileSync(p, 'utf8'));
        skills.push({ name, kind: classifySkill(fm), description: fm.description || '' });
      }
    }
  }
  const agents = [];
  const agentsDir = join(root, 'agents');
  if (existsSync(agentsDir)) {
    for (const f of readdirSync(agentsDir)) {
      if (f.endsWith('.md') && !f.startsWith('_')) agents.push(f.replace(/\.md$/, ''));
    }
  }
  skills.sort((a, b) => a.name.localeCompare(b.name));
  agents.sort();
  return { skills, agents };
}

export function counts({ skills, agents }) {
  return { skills: skills.length, agents: agents.length };
}

export function renderCatalog({ skills, agents }) {
  const byKind = (k) => skills.filter((s) => s.kind === k);
  const sec = (title, list) =>
    `### ${title} (${list.length})\n\n` +
    (list.length ? list.map((s) => `- \`${s.name}\` — ${s.description}`).join('\n') : '_none_') + '\n';
  const c = counts({ skills, agents });
  return (
    `<!-- GENERATED by scripts/build-catalog.mjs — do not edit by hand -->\n` +
    `# laravel-agent catalog\n\n` +
    `**${c.skills} skills** (${byKind('reference').length} reference, ` +
    `${byKind('scaffolder').length} scaffolder, ${byKind('utility').length} utility) · ` +
    `**${c.agents} agents**\n\n` +
    sec('Reference skills', byKind('reference')) + '\n' +
    sec('Scaffolder skills', byKind('scaffolder')) + '\n' +
    sec('Utility skills', byKind('utility')) + '\n' +
    `### Agents (${agents.length})\n\n` +
    (agents.length ? agents.map((a) => `- \`${a}\``).join('\n') : '_none_') + '\n'
  );
}
