import { test } from 'node:test';
import assert from 'node:assert/strict';
import { parseFrontmatter, classifySkill, renderCatalog, counts, applyCounts } from './build-catalog.mjs';

test('parseFrontmatter reads top-level scalar keys', () => {
  const fm = parseFrontmatter('---\nname: x\ndescription: does y\ncontext: fork\n---\nbody');
  assert.equal(fm.name, 'x');
  assert.equal(fm.description, 'does y');
  assert.equal(fm.context, 'fork');
});

test('classifySkill derives kind from frontmatter only', () => {
  assert.equal(classifySkill({ context: 'fork' }), 'scaffolder');
  assert.equal(classifySkill({ 'disable-model-invocation': 'true' }), 'utility');
  assert.equal(classifySkill({ description: 'patterns' }), 'reference');
});

test('renderCatalog and counts summarize a scan result', () => {
  const data = {
    skills: [
      { name: 'laravel-database', kind: 'reference', description: 'db' },
      { name: 'laravel-feature', kind: 'scaffolder', description: 'feature' },
      { name: 'git-commit', kind: 'utility', description: 'commit' },
    ],
    agents: ['laravel-feature'],
  };
  assert.deepEqual(counts(data), { skills: 3, agents: 1 });
  const md = renderCatalog(data);
  assert.match(md, /GENERATED by scripts\/build-catalog\.mjs/);
  assert.match(md, /3 skills/);
  assert.match(md, /git-commit/);
});

test('parseFrontmatter handles folded block scalar (description: >)', () => {
  const yaml = '---\nname: laravel-api\ndescription: >\n  Build REST APIs with versioning.\n  Use for API endpoints.\ncontext: fork\n---\nbody';
  const fm = parseFrontmatter(yaml);
  assert.equal(fm.name, 'laravel-api');
  assert.match(fm.description, /Build REST APIs/);
  assert.equal(fm.context, 'fork');
});

test('applyCounts replaces only the marker block', () => {
  const src = 'intro\n<!-- catalog:counts -->OLD<!-- /catalog:counts -->\noutro';
  const out = applyCounts(src, { skills: [1, 2], agents: [1] });
  assert.match(out, /<!-- catalog:counts -->2 skills · 1 agents<!-- \/catalog:counts -->/);
  assert.match(out, /intro/);
  assert.match(out, /outro/);
});
